import Gallery from "@/components/constants/Gallery";
import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

export default function GalleryPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Gallery />
    </>
  );
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["home", "gallery"], null, [
        "en",
        "tr",
      ])),
    },
  };
}
