import Gallery from "@/components/constants/Gallery";
import Head from "next/head";

export default function GalleryPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Gallery />
    </>
  );
}
