import Home from "@/components/layouts/Home";
import Head from "next/head";
import fs from "fs/promises";

export default function HomePage(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home listings={props.listings.data} />
    </>
  );
}
export async function getStaticProps() {
  const filePath = "./data.json";
  const rawData = await fs.readFile(filePath, "utf8");
  const data = JSON.parse(rawData);

  return {
    props: {
      listings: {
        data,
      },
    },
  };
}
